### ISSUE TITLE
Monorepo Checklist

### ISSUE THREAD

**Issue by 0xalecks** [BeanstalkFarms/Beanstalk#178]
This issue is a WIP.

List of tasks to be looked at after monorepo is merged in
- [x] Archive old repos
- [x] Centralize and share ABIs, typedefs, graphql defs, etc... (Generated asset location and creation (done in #239 )
- [x] #236
- [x] #240
- [x] #241
- [x] Post Install scripts (bundle in here the previous post-install scripts. look at archived repos)
- [x] Yarn scripts ( in #239)
  - [x] Bootstrap dev env (one time run after git pull)
  - [x] Start dev env (generate, compile, start, etc..)
- [x] #237
- [x] What does a Github release represent in this repo now?
- [x] Add dev-graph-node project ( in #181 )
- [x] Review Github permissions (@silochad @0xalecks )

**Comment by silochad** [comment]
Began archiving some of the independent repos but realized that prevents us from transferring issues using Github UI. I'm going to unarchive, close some issues out, and figure out whether to manually transfer or write a script

**Comment by silochad** [comment]
README and template work ongoing in #236 236
