### ISSUE TITLE
Add BIPs 1-19 to the governance page

### ISSUE THREAD

**Issue by imcoolbean** [BeanstalkFarms/Beanstalk#213]
## Description
The governance page currently does not include BIPs that were proposed before the exploit (BIPs 1-19). The markdown files for these BIPs live here: https://github.com/BeanstalkFarms/Beanstalk/tree/master/bips. 

## Tasks:
- [ ] Create Netlify function to pull all BIPs
- [ ] Create Netlify function to pull a specific BIP
- [ ] Merge old BIP data with the new BIPs

## To Discuss:
- Query local files vs github files. ex: https://raw.githubusercontent.com/BeanstalkFarms/Beanstalk/master/bips/bip-0.md
