### ISSUE TITLE
BASIN-UI: Tracking

### ISSUE THREAD

**Issue by 0xalecks** [BeanstalkFarms/Beanstalk#439]
- [ ] Liquidity page borked if zero liquidity, ie brand new wells
- [ ] Make UI more responsive (esp the liquidity pages)
- [x] Get production Alchemy key
- [x] double check loading wells and history from chain, how far back we load from.
- [x] Errors in add and remove liquidity components if input values exceed balance
- [ ] Hide selected token in output
- [x] refresh balance after swap
- [x] update logos
- [x] allow doing quotes w/o a connected account
- [x] token marquee
- [x] handle network stuff better (reload after change, warn if bad network, etc...)
- [x] add token revocation to Dev page
- [x] Reload after connecting wallet
- [x] mobile layout 
- [x] ETH support - unwrap, pending pipeline upgrade
- [x] changing out token causes a reverse quote
- [x] redo quote after changing slippage
- [x] disable swap button if balance is not right
- [x] ETH support (wrap)
- [x] Add/Remove liquidity page
- [x] Charts
- [x] Debounce inputs
- [x] Toast notifications for transactions
- [x] Wells page - figure out liquidity/pumps/well function data
- [x] SDK - fix add liquidity validation: allow just one to be non-zero
- [x] update formatting of toHuman()
- [x] sdk-wells tests
- [x] Wells (aka Liquidity) page (tabs with my position) 
- [x] get USD value of X
- [x] debug system

Deferred
- [ ] permit approvals
- [ ] double check state of swap if user changes accounts mid swap/quote. (do quote, change accounts, need to redo quote cause approvals are not right now)
